<?php
/**
 * Implements hook_action_info().
 */
function ddc_vbo_actions_action_info() {
  return array(

    // Highlight article action
    'highlight_add_action' => array(
      'type' => 'entity', 
      'label' => t('Highlight content'),
      'configurable' => FALSE, 
      'behavior' => array('changes_property'),
      'triggers' => array('any'),
    ),

  'highlight_remove_action' => array(
      'type' => 'entity', 
      'label' => t('Remove highlight'),
      'configurable' => FALSE, 
      'behavior' => array('changes_property'),
      'triggers' => array('any'),
    ),

  );
}

/**
 * Set the field to true to highlight the article
 */
function highlight_add_action($entity, $context) {
  $entity->field_special['und'][0]['value'] = 1;
}

/**
 * Set the field to false to remove highlight
 */
function highlight_remove_action($entity, $context) {
  $entity->field_special['und'][0]['value'] = 0;
}

?>

